theme = "gruvbox_transparent"

[editor]
scrolloff = 50
line-number = "relative"
shell = ["fish", "-c"]
cursorline = true
cursorcolumn = true
continue-comments = false
auto-format = false
completion-timeout = 5
true-color = true
undercurl = true
rulers = [ 80 ]
bufferline = "always"
color-modes = true
popup-border = "none"
jump-label-alphabet = "strnieahcdluoy"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
mode.normal = " normal"
mode.insert = " insert"
mode.select = "󰫙 select"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[keys.normal]
"ret" = "goto_word"

[keys.normal.space.t]
u = [
  ":write",
  ":sh 'just update-snapshot'",
  ":redraw",
  ":reload"
]

[keys.normal.space.g]
o = [
  ":write-all",
  ":new",
  ":insert-output gitui >/dev/tty",
  ":set mouse false",
  ":set mouse true",
  ":buffer-close!",
  ":redraw",
  ":reload-all"
]
p = ":sh git push"

[keys.normal.space.e]
r = ":config-reload"
o = ":config-open"
l = ":open ~/.config/helix/languages.toml"
